# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-23 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('ONGOING', 'ONGOING'), ('FINISHED', 'FINISHED')], max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Driver')),
            ],
        ),
    ]
