# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-23 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170923_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('ONGOING', 'ONGOING'), ('FINISHED', 'FINISHED')], default='WAITING', max_length=30),
        ),
    ]
